import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import './Home.css';

function Home() {
  const navigate = useNavigate();
  const currentUser = useSelector((state) => state.user.currentUser);

  const handleGetStarted = () => {
    if (currentUser) {
      navigate('/dashboard');
    } else {
      navigate('/login');
    }
  };

  return (
    <div className="home-page">
      <div className="hero-section">
        <div className="hero-content">
          <h1 className="hero-title">
            Ace Your Next Interview with AI
          </h1>
          <p className="hero-subtitle">
            Practice with AI-powered mock interviews, get instant feedback,
            and track your progress across various topics and difficulty levels.
          </p>
          <button onClick={handleGetStarted} className="cta-button">
            Get Started
          </button>
        </div>
      </div>

      <div className="features-section">
        <h2 className="section-title">Features</h2>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">🤖</div>
            <h3>AI-Powered Questions</h3>
            <p>Get dynamic interview questions generated by Google Gemini AI</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">💡</div>
            <h3>Instant Feedback</h3>
            <p>Receive detailed feedback on your answers to improve</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📊</div>
            <h3>Track Progress</h3>
            <p>Monitor your performance and see your growth over time</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🎯</div>
            <h3>Custom Topics</h3>
            <p>Practice interviews for your target role and tech stack</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">⚡</div>
            <h3>Difficulty Levels</h3>
            <p>Choose from Easy, Medium, or Hard question difficulties</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📝</div>
            <h3>Session History</h3>
            <p>Review past sessions and learn from previous interviews</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Home;